# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b34c1c0fd51c1597b89f2d0cf34085f332d54c4470c353ef5aa63f8984a81972aa48418ef872dc394b3d8339b1bf8f7a1a9bcaa92876974b69da79804f66b73

test:
  secret_key_base: eba4154a31cfbf27da69cb14530ba610ffcf3c3611c0952e37730dc693c06d16edf4256007db9b7b4e4e2b150f2f84ac8fdeec25c59aeb649dfd97dd010ea8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
